version: "3"
services:
  node-bootstrap:
    image: aceberg/node-bootstrap
    restart: unless-stopped
    ports:
    - 8850:8850
    volumes:
    - ~/.dockerdata/icons:/app/icons  # For local icons
  wyp:
    image: aceberg/watchyourports
    restart: unless-stopped
    ports:
    - 8853:8853
    command: "-n http://YOUR_IP:8850" # Put your server IP or DNS name here
    depends_on:
      - node-bootstrap
    volumes:
    - ~/.dockerdata/WatchYourPorts:/data/WatchYourPorts       # app data (set your own path instead of dockerdata)
    environment:
      TZ: Asia/Novosibirsk    # required, default ""
      HOST: "0.0.0.0"         # optional, default: 0.0.0.0
      PORT: "8853"            # optional, default: 8853
      THEME: "grass"          # optional, default: grass
      COLOR: "dark"           # optional, default: dark